### ISSUE TITLE
有编译好的么

### ISSUE THREAD

**Issue by fuckgithubh** [iofomo/fireyer#1]
有编译好的么

**Comment by iofomo** [comment]
已经上传了

**Comment by fuckgithubh** [comment]
F:\Google下载>adb install "F:\Google下载\fireyer-1.0.2-release (1).apk"
Performing Streamed Install
adb: failed to install F:\Google下载\fireyer-1.0.2-release (1).apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2052963625.tmp/base.apk (at Binary XML file line #29): Invalid taskAffinity name Fireyer in package com.ifma.cmpt.demo.fireyer: must have at least one '.' separator] @iofomo

**Comment by fuckgithubh** [comment]
![3b140c740df2917a721a64208994aadb](https://github.com/iofomo/fireyer/assets/31642056/bcc562fe-5560-4fcc-ba68-9d925fb7b564)
@iofomo

**Comment by iofomo** [comment]
> ![3b140c740df2917a721a64208994aadb](https://private-user-images.githubusercontent.com/31642056/334469351-bcc562fe-5560-4fcc-ba68-9d925fb7b564.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDU4OTgsIm5iZiI6MTcxNjk0NTU5OCwicGF0aCI6Ii8zMTY0MjA1Ni8zMzQ0NjkzNTEtYmNjNTYyZmUtNTU2MC00ZmNjLWJhNjgtOWQ5MjVmYjdiNTY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAxMTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOTllOWMwZmIzNzlmZTEzYzYyYTc2YWU5ZTQxMzgzNmM2YTczMmZjMTYxMDE1NmQyMDEyZWY4OWZkM2I0MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ll-j0GkaFMfkSLZcwVAIAA9DWCl41dyjRw0egAYRBDc) @iofomo

any log ???

**Comment by fuckgithubh** [comment]
啥意思@ @iofomo

**Comment by iofomo** [comment]
能ADB抓个日志看看吗？

**Comment by df13954** [comment]
> 能ADB抓个日志看看吗？

遇到同样的问题，application fac：

```

2024-06-03 16:35:03.340 2074-2146/? I/ActivityTaskManager: Displayed com.ifma.cmpt.demo.fireyer/com.ifma.cmpt.demo.main.ConsoleActivity: +85ms
2024-06-03 16:35:03.340 10359-10394/? W/System.err: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
2024-06-03 16:35:03.340 10359-10394/? W/System.err:     at com.ifma.cmpt.testin.module.TstRunner.doRun(TstRunner.java:84)
2024-06-03 16:35:03.340 10359-10394/? W/System.err:     at com.ifma.cmpt.testin.module.TstRunner.access$500(TstRunner.java:18)
2024-06-03 16:35:03.340 10359-10394/? W/System.err:     at com.ifma.cmpt.testin.module.TstRunner$1.run(TstRunner.java:53)
2024-06-03 16:35:03.341 10359-10394/? W/System.err:     at java.lang.Thread.run(Thread.java:920)
2024-06-03 16:35:03.341 10359-10394/? W/System.err: Caused by: java.lang.reflect.InvocationTargetException
2024-06-03 16:35:03.341 10359-10394/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2024-06-03 16:35:03.341 10359-10394/? W/System.err:     at com.ifma.cmpt.testin.module.TstRunner.doRun(TstRunner.java:82)
2024-06-03 16:35:03.341 10359-10394/? W/System.err: 	... 3 more
2024-06-03 16:35:03.341 10359-10394/? W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
2024-06-03 16:35:03.341 10359-10394/? W/System.err:     at com.ifma.cmpt.demo.test.FireyerAccessibilityCase.tearDown(FireyerAccessibilityCase.java:30)
2024-06-03 16:35:03.341 10359-10394/? W/System.err:     at com.ifma.cmpt.testin.module.TstCaseBase.runTest(TstCaseBase.java:42)
2024-06-03 16:35:03.341 10359-10394/? W/System.err: 	... 5 more
2024-06-03 16:35:04.348 1295-1295/? W/adbd: timeout expired while flushing socket, closing
```

**Comment by iofomo** [comment]
has fixed
