### ISSUE TITLE
adb install : failed

### ISSUE THREAD

**Issue by df13954** [iofomo/fireyer#2]
adb install fireyer-1.0.2-debug.apk
Performing Streamed Install
adb: failed to install fireyer-1.0.2-debug.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1129280959.tmp/base.apk (at Binary XML file line #29): Invalid taskAffinity name Fireyer in package com.ifma.cmpt.demo.fireyer: must have at least one '.' separator]

**Comment by iofomo** [comment]
has fixed, apk files updated

**Comment by df13954** [comment]
> has fixed, apk files updated

apk-debug, 点击文件分享：2024-06-03 16:30:15.932 10125-10125/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ifma.cmpt.demo.fireyer, PID: 10125
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.ifma.cmpt.demo.fireyer.SubProvider/media/Android/data/com.ifma.cmpt.demo.fireyer/cache/test.pdf typ=application/pdf flg=0x10000001 }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1085)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1056)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:411)
        at com.ifma.cmpt.demo.main.MainActivity.openFileWithInstalledApps(MainActivity.java:93)
        at com.ifma.cmpt.demo.main.MainActivity.onClick(MainActivity.java:79)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7876)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by iofomo** [comment]
Invalid Android env ？

**Comment by df13954** [comment]
> Invalid Android env ？

A normal Android device
